version: '3.8'

services:
  db_test:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
      dockerfile: ./django_proyect/Dockerfile.prod
    ports:
      - '8000:8000'
    depends_on:
      - db_test
    env_file:
      - .env

volumes:
  db_data:
