version: '3.8'

services:
  db_test:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    # Añadimos el comando para establecer el plugin de autenticación

  web:
    build:
      context: .
      dockerfile: ./django_proyect/Dockerfile.dev
    command: gunicorn django_app.wsgi:application -b 0.0.0.0:8000 -w 1 --log-level debug --reload --reload-engine poll
    volumes:
      - ./django_proyect:/app
    ports:
      - '8000:8000'
    depends_on:
      - db_test
    env_file:
      - .env

volumes:
  db_data:
